version: '3.8'

services:
  database:
    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_secret_123
    networks:
      - mongo-local-network

networks:
  mongo-local-network:
    driver: bridge
